jobs:
  analyse_js:
    working_directory: ~/examples/native
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      - run:
          command: yarn eslint
          name: Run ESLint
      - run:
          command: yarn flow
          name: Flow
      - run:
          command: yarn jest
          name: Jest
  checkout_code:
    executor: rn/linux_js
    steps:
      - checkout
      - persist_to_workspace:
          paths: .
          root: .

orbs:
  rn: react-native-community/react-native@4.4.2
version: 2.1
workflows:
  test:
    jobs:
      - checkout_code
      - analyse_js:
          requires:
            - checkout_code
      - rn/android_build:
          build_type: release
          project_path: ~/examples/native/android
          requires:
            - analyse_js
      - rn/android_test:
          requires:
            - rn/android_build
      # - rn/ios_build:
      #     build_configuration: Release
      #     device: iPhone X
      #     name: build_ios_release
      #     project_path: ~/examples/native/Example.xcodeproj
      #     requires:
      #       - analyse_js
      #     scheme: Example
      - rn/ios_build_and_test:
          build_configuration: Release
          detox_configuration: ios.sim.release
          device: iPhone X
          project_path: ~/examples/native/Example.xcodeproj
          requires:
            - analyse_js
          scheme: Example